In [1]:
import sys

print(sys.executable)
print(sys.version)

c:\Users\lunavct\Python Projects Anahuac\Hotel_Cancellations_Streamlit\.venv\Scripts\python.exe
3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]

### Exploración de datos y creación de Dataset para el proeycto

In [2]:
import pandas as pd

df = pd.read_csv("data/hotel_bookings.csv")

df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [3]:
print("Número de filas:", df.shape[0])
print("Número de columnas:", df.shape[1])

Número de filas: 119390
Número de columnas: 32

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  str
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  str
 13  country                         118902 non-null  str
 14  market_segment                  119390 non-null  str
 15  distribution_channel            119390 non-null  str
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  str
 20  assigned_room_type              119390 non-null  str
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  str
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  str
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  str
 31  reservation_status_date         119390 non-null  str
dtypes: float64(4), int64(16), str(12)
memory usage: 37.9 MB

In [5]:
df.columns.tolist()

['hotel',
 'is_canceled',
 'lead_time',
 'arrival_date_year',
 'arrival_date_month',
 'arrival_date_week_number',
 'arrival_date_day_of_month',
 'stays_in_weekend_nights',
 'stays_in_week_nights',
 'adults',
 'children',
 'babies',
 'meal',
 'country',
 'market_segment',
 'distribution_channel',
 'is_repeated_guest',
 'previous_cancellations',
 'previous_bookings_not_canceled',
 'reserved_room_type',
 'assigned_room_type',
 'booking_changes',
 'deposit_type',
 'agent',
 'company',
 'days_in_waiting_list',
 'customer_type',
 'adr',
 'required_car_parking_spaces',
 'total_of_special_requests',
 'reservation_status',
 'reservation_status_date']

In [6]:
# PAra los datos sintéticos se seleccionan las variables importantes apra el proyecto, se definen las siguientes 12

variables_interes = [
    "hotel",
    "is_canceled",
    "lead_time",
    "stays_in_weekend_nights",
    "stays_in_week_nights",
    "adults",
    "children",
    "market_segment",
    "customer_type",
    "deposit_type",
    "adr",
    "total_of_special_requests",
    "previous_cancellations"
]

df[variables_interes].head(10)

,hotel,is_canceled,lead_time,stays_in_weekend_nights,stays_in_week_nights,adults,children,market_segment,customer_type,deposit_type,adr,total_of_special_requests,previous_cancellations
0,Resort Hotel,0,342,0,0,2,0.0,Direct,Transient,No Deposit,0.0,0,0
1,Resort Hotel,0,737,0,0,2,0.0,Direct,Transient,No Deposit,0.0,0,0
2,Resort Hotel,0,7,0,1,1,0.0,Direct,Transient,No Deposit,75.0,0,0
3,Resort Hotel,0,13,0,1,1,0.0,Corporate,Transient,No Deposit,75.0,0,0
4,Resort Hotel,0,14,0,2,2,0.0,Online TA,Transient,No Deposit,98.0,1,0
5,Resort Hotel,0,14,0,2,2,0.0,Online TA,Transient,No Deposit,98.0,1,0
6,Resort Hotel,0,0,0,2,2,0.0,Direct,Transient,No Deposit,107.0,0,0
7,Resort Hotel,0,9,0,2,2,0.0,Direct,Transient,No Deposit,103.0,1,0
8,Resort Hotel,1,85,0,3,2,0.0,Online TA,Transient,No Deposit,82.0,1,0
9,Resort Hotel,1,75,0,3,2,0.0,Offline TA/TO,Transient,No Deposit,105.5,0,0

In [7]:
#Variables Categóricas 

categoricas = [
    "hotel",
    "market_segment",
    "customer_type",
    "deposit_type"
]

for columna in categoricas:
    print(f"\n--- {columna} ---")
    print(df[columna].value_counts())

--- hotel ---
hotel
City Hotel      79330
Resort Hotel    40060
Name: count, dtype: int64

--- market_segment ---
market_segment
Online TA        56477
Offline TA/TO    24219
Groups           19811
Direct           12606
Corporate         5295
Complementary      743
Aviation           237
Undefined            2
Name: count, dtype: int64

--- customer_type ---
customer_type
Transient          89613
Transient-Party    25124
Contract            4076
Group                577
Name: count, dtype: int64

--- deposit_type ---
deposit_type
No Deposit    104641
Non Refund     14587
Refundable       162
Name: count, dtype: int64

In [8]:
# Variables Numéricas

numericas = [
    "lead_time",
    "stays_in_weekend_nights",
    "stays_in_week_nights",
    "adults",
    "children",
    "adr",
    "total_of_special_requests",
    "previous_cancellations"
]

df[numericas].describe().round(2)

,lead_time,stays_in_weekend_nights,stays_in_week_nights,adults,children,adr,total_of_special_requests,previous_cancellations
count,119390.00,119390.00,119390.00,119390.00,119386.0,119390.00,119390.00,119390.00
mean,104.01,0.93,2.50,1.86,0.1,101.83,0.57,0.09
std,106.86,1.00,1.91,0.58,0.4,50.54,0.79,0.84
min,0.00,0.00,0.00,0.00,0.0,-6.38,0.00,0.00
25%,18.00,0.00,1.00,2.00,0.0,69.29,0.00,0.00
50%,69.00,1.00,2.00,2.00,0.0,94.58,0.00,0.00
75%,160.00,2.00,3.00,2.00,0.0,126.00,1.00,0.00
max,737.00,19.00,50.00,55.00,10.0,5400.00,5.00,26.00

In [9]:
df["is_canceled"].value_counts()

is_canceled
0    75166
1    44224
Name: count, dtype: int64

In [ ]:
#proporción de cancelaciones

df["is_canceled"].value_counts(normalize=True).round(3)

#Se observa el 37% de

is_canceled
0    0.63
1    0.37
Name: proportion, dtype: float64

### Generación del dataset sintético

A partir de la estructura y las distribuciones observadas en el dataset original Hotel Booking Demand, se genera un conjunto de datos sintético de 5,000 reservaciones. Los registros no representan clientes reales y se utilizarán exclusivamente con fines académicos.

In [11]:
import numpy as np
import pandas as pd

np.random.seed(42)

n = 5000

In [13]:
datos = pd.DataFrame({
    "id_reserva": [f"RES-{i:05d}" for i in range(1, n + 1)],

    "tipo_hotel": np.random.choice(
        ["City Hotel", "Resort Hotel"],
        size=n,
        p=[0.66, 0.34]
    ),

    "dias_anticipacion": np.clip(
        np.random.gamma(shape=1.3, scale=80, size=n),
        0, 500
    ).astype(int),

    "noches_estancia": np.clip(
        np.random.poisson(lam=3.4, size=n),
        1, 14
    ),

    "numero_huespedes": np.random.choice(
        [1, 2, 3, 4],
        size=n,
        p=[0.22, 0.58, 0.15, 0.05]
    ),

    "segmento_mercado": np.random.choice(
        ["Online TA", "Offline TA/TO", "Direct", "Corporate", "Groups"],
        size=n,
        p=[0.47, 0.20, 0.12, 0.11, 0.10]
    ),

    "tipo_cliente": np.random.choice(
        ["Transient", "Transient-Party", "Contract", "Group"],
        size=n,
        p=[0.75, 0.20, 0.04, 0.01]
    ),

    "tipo_deposito": np.random.choice(
        ["No Deposit", "Non Refund", "Refundable"],
        size=n,
        p=[0.87, 0.12, 0.01]
    ),

    "tarifa_diaria": np.clip(
        np.random.normal(loc=102, scale=35, size=n),
        35, 300
    ).round(2),

    "solicitudes_especiales": np.random.choice(
        [0, 1, 2, 3, 4],
        size=n,
        p=[0.55, 0.28, 0.12, 0.04, 0.01]
    ),

    "cancelaciones_previas": np.random.choice(
        [0, 1, 2, 3],
        size=n,
        p=[0.91, 0.06, 0.02, 0.01]
    )
})

datos.head(10)

,id_reserva,tipo_hotel,dias_anticipacion,noches_estancia,numero_huespedes,segmento_mercado,tipo_cliente,tipo_deposito,tarifa_diaria,solicitudes_especiales,cancelaciones_previas
0,RES-00001,Resort Hotel,71,1,2,Online TA,Transient,No Deposit,113.99,1,0
1,RES-00002,City Hotel,14,2,1,Online TA,Transient-Party,No Deposit,92.84,1,0
2,RES-00003,City Hotel,196,2,3,Online TA,Transient-Party,Non Refund,51.99,0,0
3,RES-00004,Resort Hotel,175,4,3,Offline TA/TO,Transient-Party,No Deposit,134.67,0,3
4,RES-00005,City Hotel,51,5,2,Offline TA/TO,Transient,Non Refund,35.00,1,0
5,RES-00006,Resort Hotel,19,7,2,Offline TA/TO,Transient-Party,Non Refund,119.10,1,0
6,RES-00007,City Hotel,10,6,1,Online TA,Transient,No Deposit,55.11,1,0
7,RES-00008,Resort Hotel,13,5,2,Online TA,Transient,Non Refund,89.17,0,0
8,RES-00009,Resort Hotel,42,5,2,Online TA,Transient,No Deposit,112.70,0,0
9,RES-00010,City Hotel,165,4,1,Online TA,Transient,No Deposit,67.84,0,0

In [ ]:
#construyo una probabilidad de cancelación relacionada con algunas características, añadiendo aleatoriedad suficiente para que el resultado no sea perfectamente predecible.
# La intención es obtener una tasa cercana al 37 % observado en el dataset original, sin copiar sus registros.

In [21]:
# Puntaje base de cancelación. Un valor menos negativo, generaría más cancelaciones. Uno más negativo, genera menos.
puntaje = np.full(n, -1.20)

# Mayor anticipación incrementa el riesgo
puntaje += datos["dias_anticipacion"] * 0.004

# Historial de cancelaciones incrementa el riesgo
puntaje += datos["cancelaciones_previas"] * 0.75

# Efecto del segmento de mercado
puntaje += np.where(
    datos["segmento_mercado"] == "Online TA",
    0.35,
    0
)

puntaje += np.where(
    datos["segmento_mercado"] == "Groups",
    0.20,
    0
)

# Efecto del tipo de depósito
puntaje += np.where(
    datos["tipo_deposito"] == "Non Refund",
    0.65,
    0
)

puntaje -= np.where(
    datos["tipo_deposito"] == "Refundable",
    0.25,
    0
)

# Los clientes recurrentes o de contrato presentan menor riesgo
puntaje -= np.where(
    datos["tipo_cliente"] == "Contract",
    0.35,
    0
)

# Las solicitudes especiales indican mayor interacción con el hotel
puntaje -= datos["solicitudes_especiales"] * 0.28

# Las estancias más largas presentan un ligero incremento del riesgo
puntaje += np.where(
    datos["noches_estancia"] >= 7,
    0.20,
    0
)

# Agregar variación aleatoria
puntaje += np.random.normal(
    loc=0,
    scale=0.55,
    size=n
)

# Convertir el puntaje a una probabilidad entre 0 y 1
probabilidad_cancelacion = 1 / (1 + np.exp(-puntaje))

probabilidad_cancelacion[:10]

0    0.341533
1    0.086786
2    0.515922
3    0.877346
4    0.378562
5    0.183822
6    0.281529
7    0.419126
8    0.669272
9    0.378597
Name: dias_anticipacion, dtype: float64

In [22]:
#Se evalúa la probabilidad correspondiente a cada reservación. 1: reservación cancelada, 0: reservación no cancelada. Dos reservaciones con características similares todavía pueden tener resultados diferentes. Esto evita que el dataset sea totalmente determinista

datos["cancelada"] = np.random.binomial(
    n=1,
    p=probabilidad_cancelacion,
    size=n
)

datos.head()

,id_reserva,tipo_hotel,dias_anticipacion,noches_estancia,numero_huespedes,segmento_mercado,tipo_cliente,tipo_deposito,tarifa_diaria,solicitudes_especiales,cancelaciones_previas,cancelada
0,RES-00001,Resort Hotel,71,1,2,Online TA,Transient,No Deposit,113.99,1,0,1
1,RES-00002,City Hotel,14,2,1,Online TA,Transient-Party,No Deposit,92.84,1,0,0
2,RES-00003,City Hotel,196,2,3,Online TA,Transient-Party,Non Refund,51.99,0,0,0
3,RES-00004,Resort Hotel,175,4,3,Offline TA/TO,Transient-Party,No Deposit,134.67,0,3,1
4,RES-00005,City Hotel,51,5,2,Offline TA/TO,Transient,Non Refund,35.00,1,0,0

In [23]:
#Validar la tasa de cancelación

conteo_cancelaciones = datos["cancelada"].value_counts().sort_index()

proporcion_cancelaciones = (
    datos["cancelada"]
    .value_counts(normalize=True)
    .sort_index()
    .round(3)
)

print("Conteo:")
print(conteo_cancelaciones)

print("\nProporción:")
print(proporcion_cancelaciones)

print(
    "\nTasa de cancelación:",
    f"{datos['cancelada'].mean():.1%}"
)

#Primero se obtuvo un porcentaje de cancelación del 32% y se ajustó el puntaje base de cancelación a -1.20 para acercarse al 37% observado en el dataset original.

Conteo:
cancelada
0    3178
1    1822
Name: count, dtype: int64

Proporción:
cancelada
0    0.636
1    0.364
Name: proportion, dtype: float64

Tasa de cancelación: 36.4%

In [ ]:
#Se revisa que las relaciones tengan sentido para comprobar que las relaciones programadas aparecen en los datos.

resumen_segmentos = (
    datos.groupby("segmento_mercado")["cancelada"]
    .agg(
        reservaciones="count",
        tasa_cancelacion="mean"
    )
    .sort_values("tasa_cancelacion", ascending=False)
)

resumen_segmentos["tasa_cancelacion"] = (
    resumen_segmentos["tasa_cancelacion"] * 100
).round(1)

resumen_segmentos

                  reservaciones  tasa_cancelacion
segmento_mercado
Online TA                  2415              40.5
Groups                      450              35.6
Direct                      584              34.4
Offline TA/TO              1014              31.7
Corporate                   537              30.0

In [25]:
resumen_depositos = (
    datos.groupby("tipo_deposito")["cancelada"]
    .agg(
        reservaciones="count",
        tasa_cancelacion="mean"
    )
    .sort_values("tasa_cancelacion", ascending=False)
)

resumen_depositos["tasa_cancelacion"] = (
    resumen_depositos["tasa_cancelacion"] * 100
).round(1)

resumen_depositos

               reservaciones  tasa_cancelacion
tipo_deposito
Non Refund               642              45.5
No Deposit              4295              35.3
Refundable                63              22.2

In [26]:
tasa_global = datos["cancelada"].mean()

print(f"Tasa global de cancelación: {tasa_global:.1%}")
print("\nDistribución:")
print(datos["cancelada"].value_counts())

Tasa global de cancelación: 36.4%

Distribución:
cancelada
0    3178
1    1822
Name: count, dtype: int64

In [27]:
datos_limpios_generados = datos.copy()

In [28]:
datos_app = datos.copy()

In [29]:
# Se generan 25 valores faltantes en tarifa_diaria: 0.5 % y 15 valores faltantes en tipo_cliente: 0.3 %

np.random.seed(42)

indices_tarifa = np.random.choice(
    datos_app.index,
    size=25,
    replace=False
)

indices_cliente = np.random.choice(
    datos_app.index.difference(indices_tarifa),
    size=15,
    replace=False
)

datos_app.loc[indices_tarifa, "tarifa_diaria"] = np.nan
datos_app.loc[indices_cliente, "tipo_cliente"] = np.nan

In [ ]:
#Generar duplicados

duplicados = datos_app.sample(
    n=8,
    random_state=42
).copy()

datos_app = pd.concat(
    [datos_app, duplicados],
    ignore_index=True
)

#El dataset final tiene ahora 5008  registros

In [31]:
print("Dimensiones finales:", datos_app.shape)

print("\nValores nulos:")
print(datos_app.isnull().sum())

print("\nFilas duplicadas:")
print(datos_app.duplicated().sum())

Dimensiones finales: (5008, 12)

Valores nulos:
id_reserva                 0
tipo_hotel                 0
dias_anticipacion          0
noches_estancia            0
numero_huespedes           0
segmento_mercado           0
tipo_cliente              15
tipo_deposito              0
tarifa_diaria             33
solicitudes_especiales     0
cancelaciones_previas      0
cancelada                  0
dtype: int64

Filas duplicadas:
8

In [32]:
ruta_salida = "data/reservas_hotel_sinteticas.csv"

datos_app.to_csv(
    ruta_salida,
    index=False
)

print(f"Dataset guardado correctamente en: {ruta_salida}")

Dataset guardado correctamente en: data/reservas_hotel_sinteticas.csv

In [33]:
df_sintetico = pd.read_csv(
    "data/reservas_hotel_sinteticas.csv"
)

print("Filas:", df_sintetico.shape[0])
print("Columnas:", df_sintetico.shape[1])
print("Duplicados:", df_sintetico.duplicated().sum())
print("Nulos totales:", df_sintetico.isnull().sum().sum())

df_sintetico.head()

Filas: 5008
Columnas: 12
Duplicados: 8
Nulos totales: 48

,id_reserva,tipo_hotel,dias_anticipacion,noches_estancia,numero_huespedes,segmento_mercado,tipo_cliente,tipo_deposito,tarifa_diaria,solicitudes_especiales,cancelaciones_previas,cancelada
0,RES-00001,Resort Hotel,71,1,2,Online TA,Transient,No Deposit,113.99,1,0,1
1,RES-00002,City Hotel,14,2,1,Online TA,Transient-Party,No Deposit,92.84,1,0,0
2,RES-00003,City Hotel,196,2,3,Online TA,Transient-Party,Non Refund,51.99,0,0,0
3,RES-00004,Resort Hotel,175,4,3,Offline TA/TO,Transient-Party,No Deposit,134.67,0,3,1
4,RES-00005,City Hotel,51,5,2,Offline TA/TO,Transient,Non Refund,35.00,1,0,0